// action types
export const SWAP_PRIMARY_SCALE_CURRENT = 'SWAP_PRIMARY_SCALE_CURRENT'
export const SWAP_PRIMARY_SCALE_FORECAST = 'SWAP_PRIMARY_SCALE_FORECAST'

export const UPDATE_CURRENT_WEATHER = 'UPDATE_CURRENT_WEATHER'
export const UPDATE_FORECAST_WEATHER = 'UPDATE_FORECAST_WEATHER'
