// action types
export const PRIMARY_SCALE_CURRENT_SWAP = 'PRIMARY_SCALE_CURRENT_SWAP'
export const PRIMARY_SCALE_FORECAST_SWAP = 'PRIMARY_SCALE_FORECAST_SWAP'

export const CURRENT_WEATHER_UPDATE = 'CURRENT_WEATHER_UPDATE'
export const FORECAST_WEATHER_UPDATE = 'FORECAST_WEATHER_UPDATE'

export const LOCATION_UPDATE = 'LOCATION_UPDATE'
